PRAGMA foreign_keys = ON;

CREATE TABLE BENCHMARK
(
ID INTEGER PRIMARY KEY ASC,
SUITE VARCHAR,
NAME VARCHAR,
DESCRIPTION VARCHAR,
CTG_ID INTEGER,
CTG_XML CLOB
);

CREATE TABLE NOC_TOPOLOGY
(
ID INTEGER PRIMARY KEY ASC,
NAME VARCHAR,
DESCRIPTION VARCHAR,
SIZE VARCHAR
);

CREATE TABLE MAPPER
(
ID INTEGER PRIMARY KEY ASC,
NAME VARCHAR,
DESCRIPTION VARCHAR,
BENCHMARK INTEGER,
NOC_TOPLOGY INTEGER,
MAPPING_XML VARCHAR,
RUNTIME INTEGER,
FOREIGN KEY(BENCHMARK) REFERENCES BENCHMARK(ID),
FOREIGN KEY(NOC_TOPLOGY) REFERENCES NOC_TOPLOGY(ID)
);

